[package]
name = "fuzz"
version = "0.1.0"
edition = "2021"

[dependencies]
afl = "*"
ponjika = { path = "../" }

[[bin]]
name = "test_english_date"
path = "src/test_english_date.rs"

[[bin]]
name = "test_bengali_date"
path = "src/test_bengali_date.rs"

